In [3]:
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
from matplotlib import rc
rc('font', family='AppleGothic')
import matplotlib
matplotlib.rcParams['axes.unicode_minus'] = False

from sklearn.preprocessing import StandardScaler
from scipy.cluster.hierarchy import linkage,dendrogram,fcluster
from sklearn.cluster import KMeans,DBSCAN
from sklearn.metrics import silhouette_samples, silhouette_score
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

from IPython.display import display
pd.options.display.max_columns = None

In [4]:
memberA = pd.read_csv('memberA.csv')
memberB = pd.read_csv('memberB.csv')
memberC = pd.read_csv('memberC.csv')
memberD = pd.read_csv('memberD.csv')

In [27]:
mA=  memberA.drop(['성별','연령대_4560대','조합원상태','연령',"구","동","회원번호","연령60이상",'주말'],axis=1,inplace=False)
mA = pd.get_dummies(mA)
mA_scaled = mA.loc[:,['방문횟수','구매금액','1회당평균구매물품수','거리','평일']]
mA.loc[:,['방문횟수','구매금액','1회당평균구매물품수','거리','평일']] = scaler.fit_transform(mA_scaled)

In [17]:
avg = {}
for i in range(2,10):
    clus=KMeans(i, random_state =0)
    clus.fit(mA)
    cluster_kmeans=[j+1 for j in clus.labels_]
    mA["ClusterKmeans"]=cluster_kmeans
    
    average_score = silhouette_score(mA.drop(['ClusterKmeans'], axis = 1), mA['ClusterKmeans'])
    avg[i] = average_score
    print(i,":", avg[i])

2 : 0.2363109898341868
3 : 0.31206035968265683
4 : 0.3685660612297139
5 : 0.39350470671520094
6 : 0.3215509303044305
7 : 0.29022205965049724
8 : 0.25045194841790575
9 : 0.2637915956271374

In [28]:
clus=KMeans(5, random_state= 0)
clus.fit(mA)
cluster_kmeans=[j+1 for j in clus.labels_]
mA["ClusterKmeans"]=cluster_kmeans

In [29]:
ds_summary_km=mA.groupby("ClusterKmeans").agg(["mean"])
level0=ds_summary_km.columns.get_level_values(0)
level1=ds_summary_km.columns.get_level_values(1)
ds_summary_km.columns=level0+"_"+level1
ds_summary_km.reset_index(inplace=True)
ds_summary_km

,ClusterKmeans,배송서비스신청여부_mean,모바일알람여부_mean,Gold_member_mean,구매금액_mean,방문횟수_mean,간식_mean,건강_mean,과실_mean,기타_mean,반찬_mean,생활용품_mean,서류_mean,수산_mean,양념/가루_mean,음료_mean,잡곡_mean,주곡_mean,주류_mean,채소_mean,축산물_mean,평일_mean,1회당평균구매물품수_mean,거리_mean,연령대_20대이하_mean,연령대_30대_mean,연령대_40대_mean,연령대_50대_mean,연령대_60대_mean,연령대_70대이상_mean,구매매장_매장A_mean
0,1,0.108742,0.083156,0.017058,0.062489,0.072430,0.171213,0.019135,0.032617,0.000964,0.128822,0.058416,0.008538,0.065539,0.058750,0.055790,0.016087,0.015720,0.002028,0.206085,0.158163,0.600239,0.174374,0.145078,0.000000,0,0,1,0,0.000000,1
1,2,0.091270,0.035714,0.015873,0.060578,0.074823,0.163121,0.019352,0.035694,0.000504,0.125906,0.043510,0.007811,0.082960,0.078768,0.053982,0.019229,0.020685,0.001450,0.235431,0.107629,0.630177,0.169261,0.159640,0.000000,0,0,0,1,0.000000,1
2,3,0.087739,0.080990,0.006749,0.043153,0.059258,0.190156,0.027846,0.022902,0.002072,0.127686,0.067995,0.010058,0.073636,0.046156,0.080016,0.013068,0.017288,0.003662,0.166765,0.149568,0.645699,0.160957,0.125867,0.000000,0,1,0,0,0.000000,1
3,4,0.065315,0.072072,0.004505,0.032854,0.044747,0.239010,0.015548,0.022592,0.002394,0.124026,0.065954,0.011052,0.080238,0.050080,0.088589,0.010212,0.015275,0.003852,0.127873,0.143307,0.625153,0.159629,0.176145,0.000000,1,0,0,0,0.000000,1
4,5,0.103448,0.068966,0.000000,0.057084,0.075821,0.150840,0.005894,0.019484,0.000988,0.145681,0.049495,0.014186,0.096143,0.053097,0.033160,0.024592,0.021106,0.001280,0.247822,0.136232,0.576767,0.160664,0.155532,0.146552,0,0,0,0,0.853448,1

In [5]:
mB=  memberB.drop(['성별','연령대_4560대','조합원상태','연령',"구","동","회원번호","연령60이상",'주말'],axis=1,inplace=False)
mB = pd.get_dummies(mB)
mB_scaled = mB.loc[:,['방문횟수','구매금액','1회당평균구매물품수','거리','평일']]
mB.loc[:,['방문횟수','구매금액','1회당평균구매물품수','거리','평일']] = scaler.fit_transform(mB_scaled)

clus=KMeans(5, random_state= 0)
clus.fit(mB)
cluster_kmeans=[j+1 for j in clus.labels_]
mB["ClusterKmeans"]=cluster_kmeans

ds_summary_km=mB.groupby("ClusterKmeans").agg(["mean"])
level0=ds_summary_km.columns.get_level_values(0)
level1=ds_summary_km.columns.get_level_values(1)
ds_summary_km.columns=level0+"_"+level1
ds_summary_km.reset_index(inplace=True)
ds_summary_km

,ClusterKmeans,배송서비스신청여부_mean,모바일알람여부_mean,Gold_member_mean,구매금액_mean,방문횟수_mean,간식_mean,건강_mean,과실_mean,기타_mean,반찬_mean,생활용품_mean,서류_mean,수산_mean,양념/가루_mean,음료_mean,잡곡_mean,주곡_mean,주류_mean,채소_mean,축산물_mean,평일_mean,1회당평균구매물품수_mean,거리_mean,연령대_20대이하_mean,연령대_30대_mean,연령대_40대_mean,연령대_50대_mean,연령대_60대_mean,연령대_70대이상_mean,구매매장_매장B_mean
0,1,0.080515,0.057971,0.001610,0.029438,0.045340,0.203288,0.020098,0.017862,0.002858,0.116429,0.048334,0.009823,0.069249,0.056209,0.097314,0.013738,0.018139,0.000708,0.152780,0.173171,0.617481,0.191145,0.139381,0.000000,1,0,0,0,0.000000,1
1,2,0.103448,0.068966,0.009251,0.039847,0.055188,0.191225,0.019921,0.014085,0.001777,0.131897,0.054318,0.009538,0.084448,0.056836,0.081574,0.015687,0.011625,0.001341,0.157934,0.167794,0.620787,0.204422,0.109149,0.000000,0,1,0,0,0.000000,1
2,3,0.116239,0.076923,0.017094,0.056408,0.072799,0.164229,0.020554,0.023359,0.000716,0.133216,0.039254,0.007890,0.070149,0.062392,0.056903,0.016994,0.009855,0.005576,0.225997,0.162915,0.597232,0.203414,0.119041,0.000000,0,0,1,0,0.000000,1
3,4,0.093458,0.023364,0.014019,0.048389,0.066910,0.131701,0.015181,0.026371,0.000302,0.141055,0.039951,0.010060,0.064633,0.071368,0.056158,0.015792,0.018454,0.004165,0.235973,0.168836,0.616858,0.196780,0.112279,0.051402,0,0,0,0,0.948598,1
4,5,0.141243,0.028249,0.011299,0.051301,0.069156,0.153264,0.011317,0.016910,0.000245,0.149441,0.027209,0.010612,0.067746,0.065738,0.060816,0.022466,0.015771,0.000695,0.221965,0.175806,0.627524,0.206410,0.130100,0.000000,0,0,0,1,0.000000,1

In [19]:
sum(memberB.연령대 == '20대이하')

11

In [45]:
mB20 = memberB[memberB.연령대=='50대']

In [46]:
mB=  mB20.drop(['성별','연령대_4560대','조합원상태','연령',"구","동","회원번호","연령60이상",'주말'],axis=1,inplace=False)
mB = pd.get_dummies(mB)
mB_scaled = mB.loc[:,['방문횟수','구매금액','1회당평균구매물품수','거리','평일']]
mB.loc[:,['방문횟수','구매금액','1회당평균구매물품수','거리','평일']] = scaler.fit_transform(mB_scaled)

clus=KMeans(5, random_state= 0)
clus.fit(mB)
cluster_kmeans=[j+1 for j in clus.labels_]
mB["ClusterKmeans"]=cluster_kmeans

ds_summary_km=mB.groupby("ClusterKmeans").agg(["mean"])
level0=ds_summary_km.columns.get_level_values(0)
level1=ds_summary_km.columns.get_level_values(1)
ds_summary_km.columns=level0+"_"+level1
ds_summary_km.reset_index(inplace=True)
ds_summary_km

,ClusterKmeans,배송서비스신청여부_mean,모바일알람여부_mean,Gold_member_mean,구매금액_mean,방문횟수_mean,간식_mean,건강_mean,과실_mean,기타_mean,반찬_mean,생활용품_mean,서류_mean,수산_mean,양념/가루_mean,음료_mean,잡곡_mean,주곡_mean,주류_mean,채소_mean,축산물_mean,평일_mean,1회당평균구매물품수_mean,거리_mean,연령대_50대_mean,구매매장_매장B_mean
0,1,1,0.000000,0.000000,0.115328,0.130076,0.151619,0.016133,0.029435,0.000522,0.123271,0.028859,0.009994,0.084893,0.056720,0.050565,0.017909,0.010667,0.001280,0.244614,0.173518,0.601011,0.274583,0.065939,1,1
1,2,0,0.000000,0.000000,0.005499,0.005942,0.866952,0.002024,0.000940,0.002024,0.005263,0.015245,0.004386,0.010628,0.022807,0.015182,0.000000,0.004386,0.000940,0.010338,0.038884,0.705858,0.193401,0.196095,1,1
2,3,0,0.000000,0.000000,0.019364,0.020936,0.097046,0.022834,0.021245,0.002487,0.146039,0.066673,0.004491,0.069823,0.082163,0.089968,0.009661,0.006195,0.019608,0.199244,0.162523,0.087966,0.205118,0.176154,1,1
3,4,0,0.000000,0.000000,0.037655,0.056427,0.111077,0.021479,0.021091,0.000159,0.148876,0.038391,0.009170,0.075959,0.059260,0.054448,0.022974,0.012014,0.003341,0.252105,0.169656,0.748818,0.190756,0.139168,1,1
4,5,0,0.978261,0.217391,0.226848,0.306031,0.133799,0.030691,0.053900,0.000000,0.112499,0.019872,0.006004,0.056443,0.082168,0.045088,0.002914,0.005747,0.000725,0.248085,0.202064,0.540401,0.193781,0.106592,1,1

In [54]:
mB[mB.ClusterKmeans==3]

,배송서비스신청여부,모바일알람여부,Gold_member,구매금액,방문횟수,간식,건강,과실,기타,반찬,생활용품,서류,수산,양념/가루,음료,잡곡,주곡,주류,채소,축산물,평일,1회당평균구매물품수,거리,연령대_50대,구매매장_매장B,ClusterKmeans
53,0,0,0,0.001531,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000,0.00,0.0,0.000000,0.0,0.000000,1.000000,0.000000,0.090909,0.419355,1,1,3
61,0,0,0,0.022305,0.012903,0.000000,0.0,0.0,0.0,0.375000,0.0,0.0,0.000000,0.375,0.00,0.0,0.000000,0.0,0.125000,0.125000,0.333333,0.242424,0.000000,1,1,3
75,0,0,0,0.031261,0.045161,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.100000,0.000,0.35,0.0,0.000000,0.0,0.050000,0.500000,0.375000,0.227273,0.000000,1,1,3
184,0,0,0,0.021506,0.012903,0.076923,0.0,0.0,0.0,0.307692,0.0,0.0,0.000000,0.000,0.00,0.0,0.000000,0.0,0.076923,0.538462,0.000000,0.393939,0.000000,1,1,3
197,0,0,0,0.040598,0.025806,0.000000,0.0,0.0,0.0,0.266667,0.2,0.0,0.066667,0.000,0.00,0.0,0.066667,0.0,0.266667,0.133333,0.200000,0.272727,0.000000,1,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2883,0,0,0,0.000433,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000,0.00,0.0,0.000000,0.0,1.000000,0.000000,0.000000,0.090909,0.419355,1,1,3
2908,0,0,0,0.001398,0.000000,0.500000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000,0.00,0.0,0.000000,0.0,0.500000,0.000000,0.000000,0.181818,0.354839,1,1,3
2953,0,0,0,0.012184,0.064516,0.000000,0.0,0.0,0.0,1.000000,0.0,0.0,0.000000,0.000,0.00,0.0,0.000000,0.0,0.000000,0.000000,0.090909,0.223140,0.096774,1,1,3
2957,0,0,0,0.014265,0.032258,0.105263,0.0,0.0,0.0,0.894737,0.0,0.0,0.000000,0.000,0.00,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.287879,0.419355,1,1,3
2960,0,0,0,0.000066,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000,1.00,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.090909,0.096774,1,1,3

In [28]:
avg = {}
for i in range(2,10):
    clus=KMeans(i, random_state =0)
    clus.fit(mB)
    cluster_kmeans=[j+1 for j in clus.labels_]
    mB["ClusterKmeans"]=cluster_kmeans
    
    average_score = silhouette_score(mB.drop(['ClusterKmeans'], axis = 1), mB['ClusterKmeans'])
    avg[i] = average_score
    print(i,":", avg[i])

2 : 0.1241878608830442
3 : 0.1802880083183612
4 : 0.1855854043841058
5 : 0.19761422813851462
6 : 0.1829158002370018
7 : 0.1759461160965326
8 : 0.16764119843467362
9 : 0.17463503189993212

In [22]:
mC=  memberC.drop(['성별','연령대_4560대','조합원상태','연령',"구","동","회원번호","연령60이상",'주말'],axis=1,inplace=False)
mC = pd.get_dummies(mC)
mC_scaled = mC.loc[:,['방문횟수','구매금액','1회당평균구매물품수','거리','평일']]
mC.loc[:,['방문횟수','구매금액','1회당평균구매물품수','거리','평일']] = scaler.fit_transform(mC_scaled)

clus=KMeans(5, random_state= 0)
clus.fit(mC)
cluster_kmeans=[j+1 for j in clus.labels_]
mC["ClusterKmeans"]=cluster_kmeans

ds_summary_km=mC.groupby("ClusterKmeans").agg(["mean"])
level0=ds_summary_km.columns.get_level_values(0)
level1=ds_summary_km.columns.get_level_values(1)
ds_summary_km.columns=level0+"_"+level1
ds_summary_km.reset_index(inplace=True)
ds_summary_km

,ClusterKmeans,배송서비스신청여부_mean,모바일알람여부_mean,Gold_member_mean,구매금액_mean,방문횟수_mean,간식_mean,건강_mean,과실_mean,기타_mean,반찬_mean,생활용품_mean,서류_mean,수산_mean,양념/가루_mean,음료_mean,잡곡_mean,주곡_mean,주류_mean,채소_mean,축산물_mean,평일_mean,1회당평균구매물품수_mean,거리_mean,연령대_20대이하_mean,연령대_30대_mean,연령대_40대_mean,연령대_50대_mean,연령대_60대_mean,연령대_70대이상_mean,구매매장_매장C_mean
0,1,0.091509,0.122642,0.038679,0.037841,0.089584,0.147562,0.012305,0.023857,0.001199,0.152063,0.043567,0.008170,0.075419,0.055264,0.049501,0.023218,0.015540,0.000988,0.207524,0.183826,0.616135,0.087781,0.114434,0.000000,0,0,1,0,0.000000,1
1,2,0.088496,0.023599,0.029499,0.030416,0.082476,0.117543,0.007419,0.028723,0.001409,0.156707,0.030639,0.009970,0.061494,0.081125,0.038015,0.022994,0.021661,0.000094,0.253385,0.168821,0.613661,0.083852,0.093289,0.050147,0,0,0,0,0.949853,1
2,3,0.042553,0.101377,0.012516,0.020879,0.062978,0.202294,0.010183,0.022174,0.000803,0.144627,0.036715,0.014041,0.060641,0.055302,0.090023,0.006387,0.014435,0.001130,0.169362,0.171884,0.630649,0.082859,0.124468,0.000000,1,0,0,0,0.000000,1
3,4,0.089027,0.039337,0.026915,0.032895,0.079831,0.163912,0.009056,0.027310,0.000695,0.145773,0.029056,0.012809,0.084037,0.064535,0.034676,0.013747,0.017969,0.001040,0.233610,0.161775,0.637697,0.092313,0.176294,0.000000,0,0,0,1,0.000000,1
4,5,0.079929,0.113085,0.030195,0.031796,0.084135,0.166507,0.020044,0.018407,0.001172,0.149671,0.046997,0.010192,0.074567,0.052578,0.066266,0.010893,0.015381,0.001416,0.188857,0.177051,0.640386,0.087150,0.098579,0.000000,0,1,0,0,0.000000,1

In [23]:
mD=  memberD.drop(['성별','연령대_4560대','조합원상태','연령',"구","동","회원번호","연령60이상",'주말'],axis=1,inplace=False)
mD = pd.get_dummies(mD)
mD_scaled = mD.loc[:,['방문횟수','구매금액','1회당평균구매물품수','거리','평일']]
mD.loc[:,['방문횟수','구매금액','1회당평균구매물품수','거리','평일']] = scaler.fit_transform(mD_scaled)

clus=KMeans(5, random_state= 0)
clus.fit(mD)
cluster_kmeans=[j+1 for j in clus.labels_]
mD["ClusterKmeans"]=cluster_kmeans

ds_summary_km=mD.groupby("ClusterKmeans").agg(["mean"])
level0=ds_summary_km.columns.get_level_values(0)
level1=ds_summary_km.columns.get_level_values(1)
ds_summary_km.columns=level0+"_"+level1
ds_summary_km.reset_index(inplace=True)
ds_summary_km

,ClusterKmeans,배송서비스신청여부_mean,모바일알람여부_mean,Gold_member_mean,구매금액_mean,방문횟수_mean,간식_mean,건강_mean,과실_mean,기타_mean,반찬_mean,생활용품_mean,서류_mean,수산_mean,양념/가루_mean,음료_mean,잡곡_mean,주곡_mean,주류_mean,채소_mean,축산물_mean,평일_mean,1회당평균구매물품수_mean,거리_mean,연령대_20대이하_mean,연령대_30대_mean,연령대_40대_mean,연령대_50대_mean,연령대_60대_mean,연령대_70대이상_mean,구매매장_매장D_mean
0,1,0.104895,0.083916,0.013986,0.046662,0.064941,0.152869,0.017343,0.028950,0.000948,0.132546,0.044324,0.009842,0.084673,0.080936,0.044282,0.014379,0.014108,0.000398,0.220055,0.154347,0.641014,0.127307,0.162134,0.000000,0.000000,0,1,0.000000,0.000000,1
1,2,0.087447,0.086037,0.015515,0.042042,0.061695,0.173424,0.015500,0.024020,0.002139,0.125002,0.066935,0.009099,0.069499,0.059165,0.067557,0.014048,0.015574,0.001078,0.183748,0.171803,0.653837,0.126270,0.164982,0.000000,0.000000,1,0,0.000000,0.000000,1
2,3,0.065693,0.062044,0.000000,0.032320,0.045969,0.194920,0.020112,0.028223,0.000606,0.101370,0.061226,0.009505,0.070957,0.055560,0.095415,0.008139,0.012350,0.002611,0.161607,0.173750,0.643007,0.136033,0.228812,0.010949,0.989051,0,0,0.000000,0.000000,1
3,4,0.136612,0.038251,0.024590,0.050357,0.075781,0.143754,0.010248,0.031199,0.000520,0.146012,0.030820,0.009190,0.091631,0.065853,0.039819,0.026756,0.016552,0.001191,0.241102,0.145354,0.639828,0.125110,0.130844,0.005464,0.000000,0,0,0.994536,0.000000,1
4,5,0.095785,0.019157,0.019157,0.061442,0.093784,0.121174,0.009150,0.029301,0.003868,0.174506,0.021302,0.011970,0.071792,0.066484,0.048950,0.021089,0.019247,0.001139,0.255142,0.144888,0.640058,0.121254,0.093550,0.011494,0.000000,0,0,0.000000,0.988506,1